# Generated by Django 4.1 on 2022-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=200, unique=True)),
                ('Referrals', models.IntegerField(blank=True, null=True)),
                ('Total_deposits', models.IntegerField(blank=True, null=True)),
                ('Total_payouts', models.IntegerField(blank=True, null=True)),
                ('Total_structure', models.IntegerField(blank=True, null=True)),
                ('Airdrops_total', models.IntegerField(blank=True, null=True)),
                ('Airdrops_received', models.IntegerField(blank=True, null=True)),
                ('Team_address', models.IntegerField(blank=True, null=True)),
                ('Ranking', models.IntegerField(blank=True, null=True)),
                ('Team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Team_benefits', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
